# Generated by Django 3.0.3 on 2020-02-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_title', models.CharField(max_length=50)),
                ('lecture_professor_name', models.CharField(max_length=10)),
                ('university_name', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=50)),
                ('lecture_scoring', models.CharField(max_length=50)),
                ('number_of_tests', models.CharField(max_length=50)),
                ('meeting', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_name', models.CharField(max_length=50)),
                ('professor_educational_background', models.CharField(max_length=50)),
                ('professor_spec', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Show_lectures_in_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_title', models.CharField(max_length=50)),
                ('professor_name', models.CharField(max_length=50)),
                ('lecture_scoring', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
    ]
